package edu.uci.eecs.crowdsafe.graph.data.graph;

public enum MetaNodeType {
	NORMAL("N", true),
	SINGLETON("S"),
	TRAMPOLINE("T", true),
	RETURN("R", true),
	SIGNAL_HANDLER("SH", true),
	SIGRETURN("SR", true),
	CLUSTER_ENTRY("E"), // not generated by the VM
	CLUSTER_EXIT("X"); // not generated by the VM

	public final String code;
	public final boolean isExecutable;

	private MetaNodeType(String code) {
		this(code, false);
	}

	private MetaNodeType(String code, boolean isExecutable) {
		this.code = code;
		this.isExecutable = isExecutable;
	}
}
