#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "ahl <graph-dir> (executes 'AdHocGraphAnalyze | less')"
}

check_help $1 usage

append_classpath "CROWD_SAFE_COMMON_DIR"
append_classpath "CROWD_SAFE_GRAPH_DIR"
append_classpath "CROWD_SAFE_MERGE_DIR"

main_class="edu.uci.plrg.cfi.x86.graph.main.AdHocGraphAnalyzer"

#echo "java -cp $cp $main_class $@"
(java -Xms512M -Xmx1536M -cp $cp $main_class $@) | less 

