#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "print-graph { -c | -e } <run-dir>"
}

check_help $1 usage

while getopts "le:c:" option
do
  case $option in
    e ) type="e:"; run_dir=$OPTARG;;
    c ) type="c:"; run_dir=$OPTARG;;
    l ) logfile=$OPTARG;;
    * ) usage; exit;;
  esac
done
shift $(( $OPTIND - 1 ))

[ -z "$type" ] && echo "Please specify a graph format" && usage && exit

append_classpath "CROWD_SAFE_COMMON_DIR"
append_classpath "CROWD_SAFE_GRAPH_DIR"

main_class="edu.uci.eecs.crowdsafe.graph.main.GraphSummaryPrinter"

[ -z $run_dir ] && usage && exit

[ -z $logfile ] && logfile="print.log"
echo "Logging to "$logfile

output_file=$run_dir"/graph-summary.log"

#echo "java -cp $cp $main_class $@"
java -cp $cp $main_class -o $output_file $type$run_dir &> $logfile

