#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "transform-graph [ -l <log-file> ]"
  echo "\t{ -i <input-file> -o <output-file> | <input-file> }"
}

check_help $1 usage

append_classpath "CROWD_SAFE_COMMON_DIR"
append_classpath "CROWD_SAFE_GRAPH_DIR"
append_classpath "CROWD_SAFE_MERGE_DIR"

main_class="edu.uci.eecs.crowdsafe.graph.data.graph.transform.RawGraphTransformer"

#echo "java -cp $cp $main_class $@"
java -Xms512M -Xmx1536M -cp $cp $main_class $@

